package com.shopfever.model.hbm;

// Generated Sep 7, 2014 11:54:10 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SfCustomerAddress generated by hbm2java
 */
@Entity
@Table(name = "sf_customer_address", catalog = "shop_fever")
public class SfCustomerAddress implements java.io.Serializable {

	private Integer addressId;
	private SfCustomer sfCustomer;
	private String addressLine1;
	private String addressLine2;
	private String addressLine3;
	private String city;
	private String state;
	private Integer pincode;

	public SfCustomerAddress() {
	}

	public SfCustomerAddress(SfCustomer sfCustomer, String addressLine1) {
		this.sfCustomer = sfCustomer;
		this.addressLine1 = addressLine1;
	}

	public SfCustomerAddress(SfCustomer sfCustomer, String addressLine1,
			String addressLine2, String addressLine3, String city,
			String state, Integer pincode) {
		this.sfCustomer = sfCustomer;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.addressLine3 = addressLine3;
		this.city = city;
		this.state = state;
		this.pincode = pincode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "address_id", unique = true, nullable = false)
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(Integer addressId) {
		this.addressId = addressId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public SfCustomer getSfCustomer() {
		return this.sfCustomer;
	}

	public void setSfCustomer(SfCustomer sfCustomer) {
		this.sfCustomer = sfCustomer;
	}

	@Column(name = "address_line1", nullable = false, length = 45)
	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	@Column(name = "address_line2", length = 45)
	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	@Column(name = "address_line3", length = 45)
	public String getAddressLine3() {
		return this.addressLine3;
	}

	public void setAddressLine3(String addressLine3) {
		this.addressLine3 = addressLine3;
	}

	@Column(name = "city", length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "pincode")
	public Integer getPincode() {
		return this.pincode;
	}

	public void setPincode(Integer pincode) {
		this.pincode = pincode;
	}

}
