package com.shopfever.model.hbm;

// Generated Sep 7, 2014 11:54:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SfOrder generated by hbm2java
 */
@Entity
@Table(name = "sf_order", catalog = "shop_fever")
public class SfOrder implements java.io.Serializable {

	private Integer orderId;
	private SfCustomer sfCustomer;
	private Date orderDate;
	private String status;
	private String discountCode;
	private Set<SfOrderItem> sfOrderItems = new HashSet<SfOrderItem>(0);

	public SfOrder() {
	}

	public SfOrder(SfCustomer sfCustomer, Date orderDate) {
		this.sfCustomer = sfCustomer;
		this.orderDate = orderDate;
	}

	public SfOrder(SfCustomer sfCustomer, Date orderDate, String status,
			String discountCode, Set<SfOrderItem> sfOrderItems) {
		this.sfCustomer = sfCustomer;
		this.orderDate = orderDate;
		this.status = status;
		this.discountCode = discountCode;
		this.sfOrderItems = sfOrderItems;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "order_id", unique = true, nullable = false)
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public SfCustomer getSfCustomer() {
		return this.sfCustomer;
	}

	public void setSfCustomer(SfCustomer sfCustomer) {
		this.sfCustomer = sfCustomer;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "order_date", nullable = false, length = 0)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Column(name = "status", length = 45)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "discount_code", length = 45)
	public String getDiscountCode() {
		return this.discountCode;
	}

	public void setDiscountCode(String discountCode) {
		this.discountCode = discountCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sfOrder")
	public Set<SfOrderItem> getSfOrderItems() {
		return this.sfOrderItems;
	}

	public void setSfOrderItems(Set<SfOrderItem> sfOrderItems) {
		this.sfOrderItems = sfOrderItems;
	}

}
