package com.shopfever.model.hbm;

// Generated Sep 7, 2014 11:54:10 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SfOrderItem generated by hbm2java
 */
@Entity
@Table(name = "sf_order_item", catalog = "shop_fever")
public class SfOrderItem implements java.io.Serializable {

	private int orderItemId;
	private SfProduct sfProduct;
	private SfOrder sfOrder;
	private int quantity;

	public SfOrderItem() {
	}

	public SfOrderItem(int orderItemId, SfProduct sfProduct, SfOrder sfOrder,
			int quantity) {
		this.orderItemId = orderItemId;
		this.sfProduct = sfProduct;
		this.sfOrder = sfOrder;
		this.quantity = quantity;
	}

	@Id
	@Column(name = "order_item_id", unique = true, nullable = false)
	public int getOrderItemId() {
		return this.orderItemId;
	}

	public void setOrderItemId(int orderItemId) {
		this.orderItemId = orderItemId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public SfProduct getSfProduct() {
		return this.sfProduct;
	}

	public void setSfProduct(SfProduct sfProduct) {
		this.sfProduct = sfProduct;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "order_id", nullable = false)
	public SfOrder getSfOrder() {
		return this.sfOrder;
	}

	public void setSfOrder(SfOrder sfOrder) {
		this.sfOrder = sfOrder;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
