package com.shopfever.model.hbm;

// Generated Sep 7, 2014 11:54:10 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SfProductImages generated by hbm2java
 */
@Entity
@Table(name = "sf_product_images", catalog = "shop_fever")
public class SfProductImages implements java.io.Serializable {

	private int productImagesId;
	private SfProduct sfProduct;
	private byte[] sfProductImage;
	private Date createdDt;
	private Date updatedDt;
	private Integer createdBy;
	private Integer updatedBy;

	public SfProductImages() {
	}

	public SfProductImages(int productImagesId) {
		this.productImagesId = productImagesId;
	}

	public SfProductImages(int productImagesId, SfProduct sfProduct,
			byte[] sfProductImage, Date createdDt, Date updatedDt,
			Integer createdBy, Integer updatedBy) {
		this.productImagesId = productImagesId;
		this.sfProduct = sfProduct;
		this.sfProductImage = sfProductImage;
		this.createdDt = createdDt;
		this.updatedDt = updatedDt;
		this.createdBy = createdBy;
		this.updatedBy = updatedBy;
	}

	@Id
	@Column(name = "product_images_id", unique = true, nullable = false)
	public int getProductImagesId() {
		return this.productImagesId;
	}

	public void setProductImagesId(int productImagesId) {
		this.productImagesId = productImagesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sf_product_id")
	public SfProduct getSfProduct() {
		return this.sfProduct;
	}

	public void setSfProduct(SfProduct sfProduct) {
		this.sfProduct = sfProduct;
	}

	@Column(name = "sf_product_image")
	public byte[] getSfProductImage() {
		return this.sfProductImage;
	}

	public void setSfProductImage(byte[] sfProductImage) {
		this.sfProductImage = sfProductImage;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created_dt", length = 0)
	public Date getCreatedDt() {
		return this.createdDt;
	}

	public void setCreatedDt(Date createdDt) {
		this.createdDt = createdDt;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "updated_dt", length = 0)
	public Date getUpdatedDt() {
		return this.updatedDt;
	}

	public void setUpdatedDt(Date updatedDt) {
		this.updatedDt = updatedDt;
	}

	@Column(name = "created_by")
	public Integer getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Integer createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "updated_by")
	public Integer getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Integer updatedBy) {
		this.updatedBy = updatedBy;
	}

}
